### ISSUE TITLE
Component distribution

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/ToDoista#11]
Try dividing the whole app into smaller components. For example: create a separate component for both header and footer.

**Comment by tanujatiwari** [comment]
I would love to work on this!

**Comment by paramsiddharth** [comment]
I would like to do that. Please assign me the issue.

**Comment by paramsiddharth** [comment]
This issue is unassigned at the moment. I would like to work on this. Please assign it to me.

**Comment by paramsiddharth** [comment]
I would like to work on this.
