### ISSUE TITLE
Update .gitignore

### ISSUE THREAD

**Issue by paramsiddharth** [garimasingh128/ToDoista#30]
# Update .gitignore
The `.gitignore` file needs to be updated to ignore files from within the `backend` directory too. Currently, the commits are polluted with the `backend/node_modules` directory.

**Comment by sayna3311** [comment]
I would like to work on it. Please assign this to me.

**Comment by garimasingh128** [comment]
@sayna3311 I think @paramsiddharth has already fixed it.
