### ISSUE TITLE
Adding templates for PRs and Issues

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/ToDoista#7]
- PR Template reference: https://gist.github.com/garimasingh128/f81418db6f4dbe6946e6d1abaf3ec8ec
- Issue template

**Comment by Halix267** [comment]
I would like to work on this issue. Plzz assign it to me @garimasingh128

**Comment by Kerveyfelix** [comment]
Can I work on this issue?

**Comment by Gauravmauryaios** [comment]
can I  work on this issue.?

**Comment by garimasingh128** [comment]
Already solved
