### ISSUE TITLE
Update README and beautify it

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/ToDoista#9]
- Try updating readme and link contribution guidelines and code of conduct to it
- you can add some images or fun memes
- Take inspiration from https://github.com/garimasingh128/gitsetgo
https://github.com/garimasingh128/profext/blob/master/README.md

**Comment by yashgautam9274** [comment]
I want to work on this

**Comment by paramsiddharth** [comment]
I think the README needs update in the documentation regarding how to set up a development Mongo server that the React app may connect to on port 5000. Could you assign me this issue?

**Comment by yashgautam9274** [comment]
I add code of conduct and contibution guidelines and many other thing in readme.md
I  send pull request on 1 dec

**Comment by garimasingh128** [comment]
Take help from here: https://github.com/garimasingh128/profext/blob/master/README.md
Add all the badges and the important contents in this project also.

**Comment by yashgautam9274** [comment]
ok, can you specify the content which you want to be added in readme.md file.

**Comment by Tejas1510** [comment]
@garimasingh128 can i take the issue 
The current Readme is not having a getting started guide so a new comer would find it difficult to contribute to the project , also I wish to decorate the readme with some styles and add badges which will keep track of issues opened, total pull request merged,
contributors etc

**Comment by yashgautam9274** [comment]
@Tejas1510  I am already working on this issue

**Comment by Pranav016** [comment]
Can I work on this?

**Comment by garimasingh128** [comment]
It has been solved already by https://github.com/garimasingh128/ToDoista/pull/32
If you find any issues, make a new issue and I will assign you if it's worthy!
